[target.riscv32imac-unknown-none-elf]
runner = "riscv32-elf-gdb -q -x gdb_init"
rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "riscv32imac-unknown-none-elf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
